### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by alexoslabs** [wafpassproject/wafpass#1]
Hi,

I have been cloned the wafpass repository, when I try execute the python displayed this error:

**Traceback (most recent call last):
  File "wafpass.py", line 16, in <module>
    import requests.exceptions
ImportError: No module named 'requests'**

**System Information:**
CentOS Linux release 7.3.1611
python34-3.4.5-3.el7.x86_64

**Comment by hamedeasy** [comment]
hi
To install Requests, simply run this simple command in your terminal:

$ pip install requests

**Comment by alexoslabs** [comment]
Sounds great!

Thanks!
