### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by bitian** [wafpassproject/wafpass#2]
When I run "python3 wafpass.py -u http://www.xxx.com" it shows error:
Traceback (most recent call last):
  File "wafpass.py", line 300, in <module>
    main()
  File "wafpass.py", line 120, in main
    len_req_header = int(len(''.join(req_header.headers.values()))) - int(len(req_header.headers.get('Content-Length')))
TypeError: object of type 'NoneType' has no len()

I don't know why,please help me ,thank you！

**Comment by hamedeasy** [comment]
thank you, i fix it
